language: node_js
node_js:
  - "12"
branches:
  only:
    - master
    - develop
    - "/^v.*$/"
before_script:
  - npm install
before_deploy:
  - npm run prerelease
deploy:
  - provider: releases
    edge: true
    skip_cleanup: true
    api_key:
      secure: V8Bc4L4kgo65xL2q7w8HB5CxOXsdud1Sttb5LQUfxG5N4FmOHaPcpeByydJxruUKB4v48u60QFN9Gvy3LOiyTYmMIlvHkhfqrcpTwh8q3DVqMHsLs4kExnUiQcArvGBaUNPIaguRNAlmvD3kc2K6QP9vShoTSDwEM2Tasq5yk1J8Q/yED4skCIBZzMD7c26HQjogPwa0nEKj0caBWA534XS4UxBxj1pGv9d/EO4XX5M5DZt9bcL/rF0rUK7KWrlO4kYlgrTLf7Nqs7ojASelqbpFtyPP9zAM+ZernZaF6y1QgPq0j95IOJdNaH9xQ+T9IxI/V2bRDdjCjbFpqz9EkOPYAxTAgKZHkpBdPbNlDmeWayhEqEKMiETxxaMb0z6Fa3w5I/+Zk4GpWWATwi7UWBINjAATgn5Mhzq48+JS8m0DKd5ZUmSSmlvINfKAamIb0rzsX0T3REVqRylhxP0+vUMdFdu9zbH2dXJAvgN0bWoq42pc3hed4rp6PfYmMHaWKONukg6UNgcmeVM+KgCzWQWkIbfSilX9EB5znv6zH7OCTqtIQDX2Y+kOLF1AIXeEb7Mi3VWnKEGpVeq0OQiMrBSS4xa5AYjSlCQrziaID9zCBaDBTMCLQ+4KfaaGtd350a+QBNx/pW8fsIE+X3Brqg+Ho2PsQn2X43xweXTF35Q=
    file: dist.zip
    on:
      branch: master
      tags: true
      repo: flekschas/dom-2d-camera
  - provider: npm
    edge: true
    skip_cleanup: true
    email: code@lekschas.de
    api_key:
      secure: LaHVj6ul78oMOqVSExOn2vMsAZxX9PEb/jq5E8op96qYjcig5BgNFtlm6M1aUgM0wseHKiLT7w/cPd0qkwpCe0Rf4fW9iQ6oyOd23sHHkpOomcDVknNOGn8dGd3R68Rm9lNJJxLRpGiNjAKp4WeP2LTsCqgIvOKYSu3KIpJWP2osbZm3CVDpxjS5jZes817iKbaaRQYE83mqMOjzYVICIIX5OR2ByEFFIyzHc33tNiOdTknSVHpzTGmQjSBx0gdTEw4rbd1+t8ubkxPlq7gajbCwpNvYc1YueKpApU6Eb5soq8ePyyVqvMmgJ2BC4fv1KAyMaG250WV0GOB0AF1bVmNxMWI5eHOFjEYA5t6KnPmdcXZCtZP/dH16+yMgvB0O9JO8vdEODK6+0L/mxWljNWA8uy4FhkF4GwBktcihaq0xZHtTrL30Lp+rZ5KfKvtGFEURbgi5aVgsl5UcvnVWqZtKliTui6R2/ARWNXaU+xauqodPOlaKmZ8GDcDTDRDfoJS55nLJ76KVALEzkygSweC8fblD83FDbCiMckMO6XDphpXvrE99jK9NKCVwGDg3mr7yRgmeJcZooJKHE8w5myiOp+lRGqsahpBs6ew4wuEEmXc8XS1pcYi9Nid6Rg1ZdO21irlAHSG8uOILWKlhF9sw8l3Mmoc5RVnj1o0isZg=
    on:
      branch: master
      tags: true
      repo: flekschas/dom-2d-camera
